-- BAFAFÁ CONNECT V20.4.2
-- Moderação preventiva de nomes, usuários, Resenha, salves e conversa privada.
--
-- Impacto: banco + segurança + frontend. A lista fica em schema privado e
-- nenhuma mensagem bloqueada é persistida. Denúncia, bloqueio e moderação
-- humana permanecem para contexto, novas gírias e tentativas não previstas.
--
-- Rollback: remover os cinco gatilhos, a RPC check_content_allowed e as funções
-- privadas desta migration. Manter a tabela de termos até confirmar que não há
-- dependências. O rollback reabre a possibilidade de conteúdo ofensivo.

BEGIN;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA private TO service_role;

CREATE TABLE IF NOT EXISTS private.content_moderation_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term text NOT NULL UNIQUE CHECK (term ~ '^[a-z0-9]{2,40}$'),
  category text NOT NULL CHECK (
    category IN ('profanity', 'sexual', 'racism', 'homophobia', 'transphobia')
  ),
  block_in_username_compounds boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE private.content_moderation_terms ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON private.content_moderation_terms FROM PUBLIC, anon, authenticated;
GRANT SELECT ON private.content_moderation_terms TO service_role;

INSERT INTO private.content_moderation_terms(term, category, block_in_username_compounds)
VALUES
  ('caralho', 'profanity', true),
  ('cacete', 'profanity', true),
  ('pora', 'profanity', false),
  ('merda', 'profanity', true),
  ('puta', 'profanity', false),
  ('puto', 'profanity', false),
  ('foder', 'profanity', true),
  ('fodase', 'profanity', true),
  ('buceta', 'profanity', true),
  ('xoxota', 'profanity', true),
  ('piroca', 'profanity', true),
  ('filhodaputa', 'profanity', true),
  ('tomarnocu', 'profanity', true),
  ('arombado', 'profanity', true),
  ('arombada', 'profanity', true),
  ('boquete', 'sexual', true),
  ('suruba', 'sexual', true),
  ('pornografia', 'sexual', true),
  ('porno', 'sexual', true),
  ('nude', 'sexual', false),
  ('nudes', 'sexual', false),
  ('sexo', 'sexual', false),
  ('masturbacao', 'sexual', true),
  ('punheta', 'sexual', true),
  ('orgasmo', 'sexual', false),
  ('macaco', 'racism', false),
  ('macaca', 'racism', false),
  ('crioulo', 'racism', true),
  ('crioula', 'racism', true),
  ('negrofedido', 'racism', true),
  ('pretofedido', 'racism', true),
  ('cabeloruim', 'racism', false),
  ('servicodepreto', 'racism', true),
  ('niger', 'racism', true),
  ('viado', 'homophobia', true),
  ('veado', 'homophobia', false),
  ('bicha', 'homophobia', false),
  ('boiola', 'homophobia', true),
  ('baitola', 'homophobia', true),
  ('sapatao', 'homophobia', true),
  ('marica', 'homophobia', false),
  ('viadinho', 'homophobia', true),
  ('bichinha', 'homophobia', false),
  ('fag', 'homophobia', true),
  ('fagot', 'homophobia', true),
  ('traveco', 'transphobia', true),
  ('traveca', 'transphobia', true),
  ('transfake', 'transphobia', true),
  ('trany', 'transphobia', true)
ON CONFLICT (term) DO UPDATE
SET category = EXCLUDED.category,
    block_in_username_compounds = EXCLUDED.block_in_username_compounds,
    active = true,
    updated_at = now();

CREATE OR REPLACE FUNCTION private.normalize_moderation_text(_value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog
AS $$
  SELECT translate(
    translate(
      lower(coalesce(_value, '')),
      'áàâãäéèêëíìîïóòôõöúùûüçñ',
      'aaaaaeeeeiiiiooooouuuucn'
    ),
    '0134578@$!+',
    'oieastbasit'
  );
$$;

CREATE OR REPLACE FUNCTION private.moderation_term_pattern(_term text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = pg_catalog
AS $$
  SELECT '(^|[^a-z0-9])'
    || string_agg(
      substr(_term, positions.position_number, 1) || '+',
      '[^a-z0-9]*'
      ORDER BY positions.position_number
    )
    || '([^a-z0-9]|$)'
  FROM generate_series(1, char_length(_term)) AS positions(position_number);
$$;

CREATE OR REPLACE FUNCTION private.blocked_content_category(
  _value text,
  _context text DEFAULT 'chat'
)
RETURNS text
LANGUAGE sql
STABLE
SET search_path = pg_catalog, private
AS $$
  WITH normalized AS (
    SELECT
      private.normalize_moderation_text(_value) AS spaced,
      regexp_replace(private.normalize_moderation_text(_value), '[^a-z0-9]', '', 'g') AS compact
  )
  SELECT terms.category
  FROM private.content_moderation_terms AS terms
  CROSS JOIN normalized
  WHERE terms.active
    AND (
      normalized.spaced ~ private.moderation_term_pattern(terms.term)
      OR (
        _context = 'username'
        AND terms.block_in_username_compounds
        AND position(terms.term IN normalized.compact) > 0
      )
    )
  ORDER BY
    CASE terms.category
      WHEN 'racism' THEN 1
      WHEN 'homophobia' THEN 2
      WHEN 'transphobia' THEN 3
      WHEN 'sexual' THEN 4
      ELSE 5
    END,
    char_length(terms.term) DESC
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION private.normalize_moderation_text(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.moderation_term_pattern(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.blocked_content_category(text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.normalize_moderation_text(text) TO service_role;
GRANT EXECUTE ON FUNCTION private.moderation_term_pattern(text) TO service_role;
GRANT EXECUTE ON FUNCTION private.blocked_content_category(text, text) TO service_role;

CREATE OR REPLACE FUNCTION public.check_content_allowed(
  _value text,
  _context text DEFAULT 'chat'
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, private
AS $$
DECLARE
  v_category text;
BEGIN
  IF _context NOT IN ('display_name', 'username', 'chat') THEN
    RAISE EXCEPTION 'Contexto de moderação inválido.';
  END IF;

  IF char_length(coalesce(_value, '')) > 1200 THEN
    RETURN jsonb_build_object('allowed', false);
  END IF;

  v_category := private.blocked_content_category(_value, _context);
  RETURN jsonb_build_object('allowed', v_category IS NULL);
END;
$$;

REVOKE ALL ON FUNCTION public.check_content_allowed(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_content_allowed(text, text) TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION private.tg_reject_sensitive_content()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, private
AS $$
BEGIN
  IF TG_TABLE_SCHEMA = 'public' AND TG_TABLE_NAME = 'profiles' THEN
    IF private.blocked_content_category(NEW.display_name, 'display_name') IS NOT NULL THEN
      RAISE EXCEPTION 'Esse nome não pode ser usado. Escolha um nome sem ofensas ou discriminação.';
    END IF;
    IF NEW.username IS NOT NULL
       AND private.blocked_content_category(NEW.username, 'username') IS NOT NULL THEN
      RAISE EXCEPTION 'Esse nome de usuário não pode ser usado. Escolha outro sem ofensas ou discriminação.';
    END IF;
  ELSIF TG_TABLE_SCHEMA = 'public' AND TG_TABLE_NAME IN (
    'event_chat_messages', 'private_chat_messages'
  ) THEN
    IF private.blocked_content_category(NEW.body, 'chat') IS NOT NULL THEN
      RAISE EXCEPTION 'Essa mensagem não segue as regras da comunidade. Ajuste o texto e tente de novo.';
    END IF;
  ELSIF TG_TABLE_SCHEMA = 'public' AND TG_TABLE_NAME = 'salve_requests' THEN
    IF NEW.opener IS NOT NULL
       AND private.blocked_content_category(NEW.opener, 'chat') IS NOT NULL THEN
      RAISE EXCEPTION 'Esse salve não segue as regras da comunidade. Ajuste o texto e tente de novo.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.tg_reject_sensitive_content() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.tg_reject_sensitive_content() TO service_role;

DROP TRIGGER IF EXISTS profiles_moderate_insert_v2042 ON public.profiles;
CREATE TRIGGER profiles_moderate_insert_v2042
BEFORE INSERT ON public.profiles
FOR EACH ROW EXECUTE FUNCTION private.tg_reject_sensitive_content();

DROP TRIGGER IF EXISTS profiles_moderate_update_v2042 ON public.profiles;
CREATE TRIGGER profiles_moderate_update_v2042
BEFORE UPDATE OF display_name, username ON public.profiles
FOR EACH ROW EXECUTE FUNCTION private.tg_reject_sensitive_content();

DROP TRIGGER IF EXISTS event_chat_moderate_content_v2042 ON public.event_chat_messages;
CREATE TRIGGER event_chat_moderate_content_v2042
BEFORE INSERT OR UPDATE OF body ON public.event_chat_messages
FOR EACH ROW EXECUTE FUNCTION private.tg_reject_sensitive_content();

DROP TRIGGER IF EXISTS private_chat_moderate_content_v2042 ON public.private_chat_messages;
CREATE TRIGGER private_chat_moderate_content_v2042
BEFORE INSERT OR UPDATE OF body ON public.private_chat_messages
FOR EACH ROW EXECUTE FUNCTION private.tg_reject_sensitive_content();

DROP TRIGGER IF EXISTS salve_moderate_content_v2042 ON public.salve_requests;
CREATE TRIGGER salve_moderate_content_v2042
BEFORE INSERT OR UPDATE OF opener ON public.salve_requests
FOR EACH ROW EXECUTE FUNCTION private.tg_reject_sensitive_content();

COMMIT;
